let act3 = {
  flame: {
    3: ['phoenix'],
    2: ['clinkz', 'lina'],
    1: [
      'batrider',
      'brewmaster',
      'dawnbreaker',
      'doom_bringer',
      'ember_spirit',
      'gyrocopter',
      'huskar',
      'jakiro',
      'ogre_magi',
      'nevermore',
      'snapfire',
      'abyssal_underlord',
    ],
  },
  frost: {
    3: ['ancient_apparition'],
    2: ['lich', 'tusk'],
    1: ['crystal_maiden', 'drow_ranger', 'jakiro', 'winter_wyvern'],
  },
  storm: {
    3: [],
    2: ['disruptor', 'razor', 'zuus'],
    1: ['arc_warden', 'brewmaster', 'leshrac', 'storm_spirit', 'sven'],
  },
  tide: {
    3: [],
    2: ['kunkka', 'morphling', 'tidehunter'],
    1: ['naga_siren', 'slardar', 'slark'],
  },
  nature: {
    3: [],
    2: ['earth_spirit', 'sand_king', 'tiny', 'treant'],
    1: [
      'brewmaster',
      'dark_willow',
      'earthshaker',
      'enchantress',
      'hoodwink',
      'leshrac',
      'lone_druid',
      'meepo',
      'furion',
      'night_stalker',
      'nyx_assassin',
      'obsidian_destroyer',
      'puck',
      'shredder',
      'ursa',
      'viper',
      'windrunner',
    ],
  },
  void: {
    3: ['bane'],
    2: ['faceless_void', 'obsidian_destroyer', 'nevermore', 'spectre', 'void_spirit'],
    1: [
      'chaos_knight',
      'dark_seer',
      'elder_titan',
      'enigma',
      'life_stealer',
      'muerta',
      'night_stalker',
      'slark',
      'spirit_breaker',
      'templar_assassin',
      'abyssal_underlord',
      'weaver',
    ],
  },
  blood: {
    3: ['pudge'],
    2: ['bloodseeker', 'life_stealer', 'necrolyte', 'queenofpain', 'troll_warlord'],
    1: [
      'axe',
      'beastmaster',
      'bounty_hunter',
      'bristleback',
      'broodmother',
      'centaur',
      'dazzle',
      'huskar',
      'juggernaut',
      'marci',
      'mars',
      'phantom_assassin',
      'primal_beast',
      'riki',
      'sand_king',
      'shadow_demon',
      'sniper',
      'tiny',
      'ursa',
      'weaver',
      'skeleton_king',
    ],
  },
  mystic: {
    3: [],
    2: ['alchemist', 'antimage', 'keeper_of_the_light', 'lion'],
    1: [
      'abaddon',
      'bounty_hunter',
      'chen',
      'dark_willow',
      'dawnbreaker',
      'dazzle',
      'death_prophet',
      'disruptor',
      'invoker',
      'wisp',
      'magnataur',
      'medusa',
      'muerta',
      'night_stalker',
      'ogre_magi',
      'oracle',
      'puck',
      'pugna',
      'rubick',
      'shadow_demon',
      'silencer',
      'skywrath_mage',
      'vengefulspirit',
      'winter_wyvern',
      'witch_doctor',
    ],
  },
  armor: {
    3: [],
    2: ['axe', 'doom_bringer', 'omniknight'],
    1: [
      'abaddon',
      'bristleback',
      'centaur',
      'chaos_knight',
      'chen',
      'rattletrap',
      'dawnbreaker',
      'dragon_knight',
      'drow_ranger',
      'ember_spirit',
      'faceless_void',
      'gyrocopter',
      'legion_commander',
      'luna',
      'lycan',
      'mirana',
      'nyx_assassin',
      'phantom_lancer',
      'queenofpain',
      'skywrath_mage',
      'spirit_breaker',
      'storm_spirit',
      'sven',
      'shredder',
      'treant',
      'undying',
      'visage',
      'skeleton_king',
    ],
  },
  helmet: {
    3: [],
    2: [],
    1: [
      'arc_warden',
      'rattletrap',
      'huskar',
      'legion_commander',
      'luna',
      'mars',
      'phantom_assassin',
      'silencer',
      'skywrath_mage',
      'sven',
      'techies',
      'shredder',
      'tinker',
      'troll_warlord',
      'undying',
    ],
  },
  shield: {
    3: [],
    2: ['pangolier', 'tinker'],
    1: ['abaddon', 'dragon_knight', 'luna', 'mars', 'medusa', 'nyx_assassin', 'silencer'],
  },
  robe: {
    3: [],
    2: ['oracle'],
    1: [
      'antimage',
      'crystal_maiden',
      'dark_seer',
      'dazzle',
      'death_prophet',
      'grimstroke',
      'invoker',
      'kunkka',
      'lich',
      'lina',
      'necrolyte',
      'rike',
      'storm_spirit',
      'templar_assassin',
      'vengefulspirit',
      'void_spirit',
      'warlock',
      'windrunner',
      'zuus',
    ],
  },
  cape: {
    3: [],
    2: [],
    1: [
      'crystal_maiden',
      'drow_ranger',
      'invoker',
      'legion_commander',
      'lion',
      'marci',
      'furion',
      'omniknight',
      'phantom_assassin',
      'pugna',
      'rubick',
      'shadow_demon',
      'sniper',
      'windrunner',
      'skeleton_king',
    ],
  },
  mask: {
    3: [],
    2: [],
    1: [
      'batrider',
      'bloodseeker',
      'bounty_hunter',
      'bristleback',
      'grimstroke',
      'gyrocopter',
      'juggernaut',
      'razor',
      'rubick',
      'shadow_shaman',
      'sniper',
      'templar_assassin',
    ],
  },
  fur: {
    3: [],
    2: ['earthshaker', 'magnataur', 'monkey_king'],
    1: [
      'beastmaster',
      'centaur',
      'enchantress',
      'hoodwink',
      'leshrac',
      'lone_druid',
      'lycan',
      'mirana',
      'riki',
      'spirit_breaker',
      'tusk',
      'ursa',
    ],
  },
  scale: {
    3: [],
    2: ['primal_beast', 'slardar', 'viper'],
    1: [
      'dragon_knight',
      'jakiro',
      'medusa',
      'pangolier',
      'puck',
      'slark',
      'snapfire',
      'terrorblade',
      'tidehunter',
      'abyssal_underlord',
      'venomancer',
      'winter_wyvern',
    ],
  },
  minion: {
    3: [],
    2: ['broodmother', 'enigma', 'visage', 'warlock'],
    1: [
      'beastmaster',
      'chen',
      'clinkz',
      'death_prophet',
      'enchantress',
      'wisp',
      'lycan',
      'monkey_king',
      'muerta',
      'furion',
      'undying',
      'weaver',
    ],
  },
  illusion: {
    3: [],
    2: ['naga_siren', 'phantom_lancer', 'terrorblade'],
    1: [
      'chaos_knight',
      'dark_seer',
      'elder_titan',
      'ember_spirit',
      'grimstroke',
      'hoodwink',
      'keeper_of_the_light',
      'morphling',
      'spectre',
      'vengefulspirit',
    ],
  },
  ward: {
    3: [],
    2: ['shadow_shaman', 'venomancer', 'witch_doctor'],
    1: ['rattletrap', 'earth_spirit', 'juggernaut', 'pugna', 'techies'],
  },
  partner: {
    3: [],
    2: ['meepo'],
    1: [
      'alchemist',
      'arc_warden',
      'batrider',
      'dark_willow',
      'elder_titan',
      'wisp',
      'lone_druid',
      'marci',
      'mirana',
      'ogre_magi',
      'snapfire',
      'techies',
    ],
  },
};

export default act3;
