const darkcarnival = {
    fool: {
        3: ['wisp'],
        2: ['crystal_maiden', 'enchantress','puck','techies','shredder','zuus'],
        1: [
            'dawnbreaker',
            'disruptor',
            'faceless_void',
            'gyrocopter',
            'hoodwink',
            'ogre_magi',
            'phoenix',
            'pudge',
            'ringmaster',
            'snapfire',
            'storm_spirit',
            'tiny',
        ],
    },
    magician: {
        3: ['rubick'],
        2: ['drow_ranger', 'invoker','lina', 'riki','skywrath_mage'],
        1: ['antimage','bloodseeker','clinkz','crystal_maiden','ember_spirit','hoodwink','leshrac','lich','lion','meepo','monkey_king','furion','phantom_lancer','puck','pugna','ringmaster','silencer','spectre','templar_assassin','weaver'],
    },
    high_priestess: {
        3: ['oracle'],
        2: ['bane', 'chen', 'dark_seer','furion','omniknight','outworld_devourer','shadow_shaman','void_spirit'],
        1: ['antimage', 'bloodseeker', 'dark_willow', 'enigma', 'huskar','largo','naga_siren','queenofpain','slardar','templar_assassin'],
    },
    devil: {
        3: ['doom_bringer'],
        2: ['bounty_hunter', 'grimstroke', 'leshrac','life_stealer','lion','medusa','pudge','queenofpain','shadow_demon','nevermore','abyssal_underlord'],
        1: ['alchemist', 'beastmaster', 'bristleback','huskar','invoker','lina','pangolier','razor','riki','slark','storm_spirit','terrorblade','treant','troll_warlord','warlock','zuus'],
    },
    emperor: {
        3: ['skeleton_king'],
        2: ['kunkka', 'legion_commander', 'mars', 'night_stalker','razor','silencer'],
        1: [
            'antimage',
            'centaur',
            'chen',
            'dragon_knight',
            'earth_spirit',
            'juggernaut',
            'kez',
            'luna',
            'mirana',
            'necrolyte',
            'omniknight',
            'primal_beast',
            'storm_spirit',
            'tidehunter',
            'troll_warlord',
            'abyssal_underlord',
            'ursa',
            'vengefulspirit'
        ],
    },
    lovers: {
        3: ['jakiro'],
        2: ['arc_warden', 'batrider', 'beastmaster', 'brewmaster', 'dazzle','ember_spirit','luna','meepo','naga_siren','visage'],
        1: [
            'alchemist',
            'broodmother',
            'dark_willow',
            'grimstroke',
            'hoodwink',
            'lone_druid',
            'mirana',
            'phantom_lancer',
            'skywrath_mage',
            'snapfire',
            'ursa',
            'vengefulspirit',
            'warlock'
        ],
    },
    strength: {
        3: ['sven'],
        2: ['axe', 'bristleback', 'centaur', 'earthshaker', 'elder_titan', 'juggernaut','kez','lycan','magnataur','marci','primal_beast','slardar','spectre'],
        1: [
            'clinkz',
            'dawnbreaker',
            'dragon_knight',
            'faceless_void',
            'gyrocopter',
            'kunkka',
            'mars',
            'phantom_assassin',
            'slark',
            'sniper',
            'spirit_breaker',
            'terrorblade',
            'troll_warlord',
            'tusk',
            'windrunner',
        ],
    },
    hermit: {
        3: ['abaddon'],
        2: ['earth_spirit', 'lone_druid', 'monkey_king', 'nyx_assassin','sand_king','sniper','tidehunter','tinker','tusk','viper'],
        1: [
            'axe',
            'bounty_hunter',
            'broodmother',
            'rattletrap',
            'dark_seer',
            'drow_ranger',
            'earthshaker',
            'elder_titan',
            'huskar',
            'marci',
            'morphling',
            'shadow_shaman',
            'templar_assassin',
            'treant',
            'undying',
            'void_spirit',
            'warlock',
            'windrunner',
            'winter_wyvern',
            'witch_doctor',
        ],
    },
    star: {
        3: ['keeper_of_the_light'],
        2: ['rattletrap', 'disruptor', 'enigma','largo','tiny','winter_wyvern'],
        1: [
            'alchemist',
            'arc_warden',
            'dawnbreaker',
            'dazzle',
            'death_prophet',
            'enchantress',
            'gyrocopter',
            'mirana',
            'pugna',
            'sand_king',
            'snapfire',
            'tinker',
            'treant',
            'ursa',
            'weaver',
            'windrunner',
            'witch_doctor',
        ],
    },
    wheel_of_fortune: {
        3: ['chaos_knight'],
        2: ['morphling','orge_magi','pangolier','phantom_assassin','spirit_breaker'],
        1: [
            'ancient_apparition',
            'batrider',
            'bloodseeker',
            'brewmaster',
            'broodmother',
            'death_prophet',
            'faceless_void',
            'lycan',
            'magnataur',
            'night_stalker',
            'nyx_assassin',
            'phantom_lancer',
            'phoenix',
            'slark',
            'shredder',
            'venomancer',
            'viper',
            'weaver',
        ],
    },
    death: {
        3: ['muerta'],
        2: ['ancient_apparition', 'lich','necrolyte','undying','venomancer'],
        1: ['bane', 'clinkz', 'death_prophet', 'dragon_knight', 'legion_commander', 'life_stealer', 'medusa','outworld_devourer','phoenix','pugna','ringmaster','shadow_demon','nevermore','techies','terrorblade','vengefulspirit','visage','witch_doctor'],
    },
};

export default darkcarnival;
